# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo.xci
# IP: The module: 'wr_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo.xci
# IP: The module: 'wr_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/FPGA/project/smart_car_pld2026/test/top_dual_ov5640_lcd/top_dual_ov5640_lcd.srcs/sources_1/ip/wr_fifo_1/wr_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'wr_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
