set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0/clk_wiz_0_in_context.xdc id:1 order:EARLY scoped_inst:u_clk_wiz_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/mig_7series_0/mig_7series_0/mig_7series_0_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/mig_7series_0/mig_7series_0/mig_7series_0_in_context.xdc id:2 order:EARLY scoped_inst:u_ddr3_top/u_mig_7series_0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo/wr_fifo_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/wr_fifo/wr_fifo/wr_fifo_in_context.xdc id:3 order:EARLY scoped_inst:u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_wr_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo/wr_fifo_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/wr_fifo/wr_fifo/wr_fifo_in_context.xdc id:4 order:EARLY scoped_inst:u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_wr_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo/wr_fifo_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/rd_fifo/rd_fifo/wr_fifo_in_context.xdc id:5 order:EARLY scoped_inst:u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_rd_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo/wr_fifo_in_context.xdc rfile:../../../../../prj.srcs/sources_1/ip/rd_fifo/rd_fifo/wr_fifo_in_context.xdc id:6 order:EARLY scoped_inst:u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_rd_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:E:/FPGA/project/smart_car_pld2026/my_car/prj/constrs_1/new/pin.xdc rfile:../../../../../constrs_1/new/pin.xdc id:7} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out1 -source [get_ports sys_clk] -edges {1 2 3} -edge_shift {0.000 -7.500 -15.000} [get_pins u_clk_wiz_0/clk_out1]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name u_clk_wiz_0/clk_out2 -source [get_ports sys_clk] -edges {1 2 3} -edge_shift {0.000 0.000 0.000} [get_pins u_clk_wiz_0/clk_out2]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports sys_clk]
set_property src_info {type:SCOPED_XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_clk_wiz_0]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name u_ddr3_top/u_mig_7series_0/ui_clk [get_pins u_ddr3_top/u_mig_7series_0/ui_clk]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:2 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ck_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ck_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_cke]
set_property src_info {type:SCOPED_XDC file:2 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_cke]
set_property src_info {type:SCOPED_XDC file:2 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_cs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:2 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:2 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:2 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:2 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:2 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:2 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[16]}]
set_property src_info {type:SCOPED_XDC file:2 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[17]}]
set_property src_info {type:SCOPED_XDC file:2 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[18]}]
set_property src_info {type:SCOPED_XDC file:2 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[19]}]
set_property src_info {type:SCOPED_XDC file:2 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[20]}]
set_property src_info {type:SCOPED_XDC file:2 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[21]}]
set_property src_info {type:SCOPED_XDC file:2 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[22]}]
set_property src_info {type:SCOPED_XDC file:2 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[23]}]
set_property src_info {type:SCOPED_XDC file:2 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[24]}]
set_property src_info {type:SCOPED_XDC file:2 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[25]}]
set_property src_info {type:SCOPED_XDC file:2 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[26]}]
set_property src_info {type:SCOPED_XDC file:2 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[27]}]
set_property src_info {type:SCOPED_XDC file:2 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[28]}]
set_property src_info {type:SCOPED_XDC file:2 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[29]}]
set_property src_info {type:SCOPED_XDC file:2 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[30]}]
set_property src_info {type:SCOPED_XDC file:2 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[31]}]
set_property src_info {type:SCOPED_XDC file:2 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:2 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:2 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:2 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:2 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:2 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:2 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:2 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[2]}]
set_property src_info {type:SCOPED_XDC file:2 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[3]}]
set_property src_info {type:SCOPED_XDC file:2 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_odt[0]}]
set_property src_info {type:SCOPED_XDC file:2 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:2 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:2 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_we_n]
set_property src_info {type:SCOPED_XDC file:2 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_we_n]
current_instance u_ddr3_top/u_mig_7series_0
set_property src_info {type:SCOPED_XDC file:2 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_ports -scoped_to_current_instance clk_ref_i]
set_property src_info {type:SCOPED_XDC file:2 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_ports -scoped_to_current_instance sys_clk_i]
current_instance
set_property src_info {type:SCOPED_XDC file:2 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_top/u_mig_7series_0]
current_instance u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_wr_fifo
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_wr_fifo]
current_instance u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_wr_fifo
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_wr_fifo]
current_instance u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_rd_fifo
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_rd_fifo]
current_instance u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_rd_fifo
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance rd_clk]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_ports -scoped_to_current_instance wr_clk]
current_instance
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_rd_fifo]
set_property src_info {type:XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets sys_clk]
set_property src_info {type:XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 20.000 -name sys_clk [get_ports sys_clk]
set_property src_info {type:XDC file:7 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports sys_clk]
set_property src_info {type:XDC file:7 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS15 [get_ports sys_rst_n]
set_property src_info {type:XDC file:7 line:52 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk_1]
set_property src_info {type:XDC file:7 line:73 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name cmos_pclk [get_ports cam_pclk_2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_clk_wiz_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_top/u_mig_7series_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_wr_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_wr_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_1/u_rd_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells u_ddr3_top/u_ddr3_fifo_ctrl_top/u_ddr3_fifo_ctrl_2/u_rd_fifo]
