# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tfgg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0 {
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0 {
      E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/rd_fifo_stub.v
      E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/clk_wiz_0_stub.v
      E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/mig_7series_0_stub.v
      E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/wr_fifo_stub.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/atan_lut.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/attitude_cf.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/clk_div.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/cmos_capture_data.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/ctrl_link_tx.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/dash_osd.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_fifo_ctrl.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_fifo_ctrl_top.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_rw.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_top.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/green_detect.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/i2c_dri.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_disply.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_driver.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_rgb_top.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/mode_switch.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/osd_font.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/osd_overlay.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/ov5640_dri.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/picture_size.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/rd_id.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sensor_calc.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sensor_link.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sincos_lut.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sl_uart_rx.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sl_uart_tx.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/stereo_dist.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/tracker_ctrl.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/ttc_warn.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/v1_decode.v
      E:/FPGA/project/smart_car_pld2026/my_car/rtl/top_dual_ov5640_lcd.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2018.3/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/realtime/top_dual_ov5640_lcd_synth.xdc
    rt::sdcChecksum
    set rt::top top_dual_ov5640_lcd
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.cache/wt}
    rt::set_parameter enableSplitFlowPath "E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.runs/synth_1/.Xil/Vivado-11220-LAPTOP-2K88VM5F/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
