# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/rd_fifo/rd_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] -quiet

# IP: ip/mig_7series_0_1/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc
