# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: F:/new_download/100t/100t/57_top_dual_ov5640_lcd/prj/top_dual_ov5640_lcd.srcs/constrs_1/new/pin.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/wr_fifo_1/wr_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] -quiet

# IP: ip/rd_fifo_1/rd_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] -quiet

# IP: ip/mig_7series_0_2/mig_7series_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet
