# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: ip/wr_fifo/wr_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] -quiet

# IP: ip/rd_fifo/rd_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] -quiet

# IP: ip/mig_7series_0_1/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/wr_fifo/wr_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==wr_fifo || ORIG_REF_NAME==wr_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/rd_fifo/rd_fifo.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: c:/Users/atk/Desktop/1008/DFPPRO/100T/38_ov5640_hdmi/prj/ov5640_hdmi.gen/sources_1/ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc
