# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/FPGA/project/smart_car_pld2026/my_car/prj/constrs_1/new/pin.xdc

# IP: ip/rd_fifo/rd_fifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rd_fifo || ORIG_REF_NAME==rd_fifo} -quiet] -quiet
