# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.cache/wt [current_project]
set_property parent.project_path E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/atan_lut.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/attitude_cf.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/clk_div.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/cmos_capture_data.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/ctrl_link_tx.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/dash_osd.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_fifo_ctrl.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_fifo_ctrl_top.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_rw.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ddr3_top/ddr3_top.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/green_detect.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/i2c_dri.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/i2c_ov5640_rgb565_cfg.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_disply.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_driver.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/lcd_rgb_top.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/mode_switch.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/osd_font.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/osd/osd_overlay.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/ov5640_dri/ov5640_dri.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/picture_size.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/lcd_rgb_top/rd_id.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sensor_calc.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sensor_link.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sincos_lut.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sl_uart_rx.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/sl_uart_tx.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/stereo_dist.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/tracker_ctrl.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/vision/ttc_warn.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/sensor_link/v1_decode.v
  E:/FPGA/project/smart_car_pld2026/my_car/rtl/top_dual_ov5640_lcd.v
}
read_ip -quiet E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo.xci
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/rd_fifo/rd_fifo_ooc.xdc]

read_ip -quiet E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

read_ip -quiet E:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo.xci
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/FPGA/project/smart_car_pld2026/my_car/prj/prj.srcs/sources_1/ip/wr_fifo/wr_fifo_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/FPGA/project/smart_car_pld2026/my_car/prj/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files E:/FPGA/project/smart_car_pld2026/my_car/prj/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_dual_ov5640_lcd -part xc7a100tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_dual_ov5640_lcd.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_dual_ov5640_lcd_utilization_synth.rpt -pb top_dual_ov5640_lcd_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
